name: E2E

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  e2e-default:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Test Run
        id: test-run
        uses: ./
        with:
          changed-files: |
            ./tests/data/default/src/package1/file.ts
            ./tests/data/default/src/package2/subfolder/file.ts
            ./tests/data/default/other/package4/file.ts
            ./tests/data/default/other/package5/file.ts
          all-packages: |
            ./tests/data/default/src/package1
            ./tests/data/default/src/package2
            ./tests/data/default/src/package3

      - name: Assert changed-packages
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.test-run.outputs.changed-packages }}
          expected: |
            ${{ github.workspace }}/tests/data/default/src/package1
            ${{ github.workspace }}/tests/data/default/src/package2

  e2e-all-packages-glob:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Test Run
        id: test-run
        uses: ./
        with:
          changed-files: |
            ./tests/data/default/src/package1/file.ts
            ./tests/data/default/src/package2/subfolder/file.ts
            ./tests/data/default/other/package4/file.ts
            ./tests/data/default/other/package5/file.ts
          all-packages: |
            ./tests/data/default/src/*
          all-packages-separator: ","

      - name: Assert changed-packages
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.test-run.outputs.changed-packages }}
          expected: |
            ${{ github.workspace }}/tests/data/default/src/package1
            ${{ github.workspace }}/tests/data/default/src/package2

  e2e-changed-files-separator:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Test Run
        id: test-run
        uses: ./
        with:
          changed-files: ./tests/data/default/src/package1/file.ts,./tests/data/default/src/package2/subfolder/file.ts,./tests/data/default/other/package4/file.ts,./tests/data/default/other/package5/file.ts
          changed-files-separator: ","
          all-packages: |
            ./tests/data/default/src/package1
            ./tests/data/default/src/package2
            ./tests/data/default/src/package3

      - name: Assert changed-packages
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.test-run.outputs.changed-packages }}
          expected: |
            ${{ github.workspace }}/tests/data/default/src/package1
            ${{ github.workspace }}/tests/data/default/src/package2

  e2e-empty-changed-files:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Test Run
        id: test-run
        uses: ./
        with:
          changed-files: ""
          all-packages: |
            ./tests/data/default/src/package1
            ./tests/data/default/src/package2
          package-dependencies-resolution-method: all

      - name: Assert changed-packages
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.test-run.outputs.changed-packages }}
          expected: |
            ${{ github.workspace }}/tests/data/default/src/package1
            ${{ github.workspace }}/tests/data/default/src/package2

  e2e-all-packages-separator:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Test Run
        id: test-run
        uses: ./
        with:
          changed-files: |
            ./tests/data/default/src/package1/file.ts
            ./tests/data/default/src/package2/subfolder/file.ts
            ./tests/data/default/other/package4/file.ts
            ./tests/data/default/other/package5/file.ts
          all-packages: ./tests/data/default/src/package1,./tests/data/default/src/package2,./tests/data/default/src/package3
          all-packages-separator: ","

      - name: Assert changed-packages
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.test-run.outputs.changed-packages }}
          expected: |
            ${{ github.workspace }}/tests/data/default/src/package1
            ${{ github.workspace }}/tests/data/default/src/package2

  e2e-changed-packages-relative-path:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Test Run
        id: test-run
        uses: ./
        with:
          changed-files: |
            ./tests/data/default/src/package1/file.ts
            ./tests/data/default/src/package2/subfolder/file.ts
            ./tests/data/default/other/package4/file.ts
            ./tests/data/default/other/package5/file.ts
          all-packages: |
            ./tests/data/default/src/package1
            ./tests/data/default/src/package2
            ./tests/data/default/src/package3
          changed-packages-relative-path: true

      - name: Assert changed-packages
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.test-run.outputs.changed-packages }}
          expected: |
            tests/data/default/src/package1
            tests/data/default/src/package2

  e2e-changed-packages-list-separator:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Test Run
        id: test-run
        uses: ./
        with:
          changed-files: |
            ./tests/data/default/src/package1/file.ts
            ./tests/data/default/src/package2/subfolder/file.ts
            ./tests/data/default/other/package4/file.ts
            ./tests/data/default/other/package5/file.ts
          all-packages: |
            ./tests/data/default/src/package1
            ./tests/data/default/src/package2
            ./tests/data/default/src/package3
          changed-packages-list-separator: ","

      - name: Assert changed-packages
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.test-run.outputs.changed-packages }}
          expected: ${{ github.workspace }}/tests/data/default/src/package1,${{ github.workspace }}/tests/data/default/src/package2

  e2e-changed-packages-format-json:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Test Run
        id: test-run
        uses: ./
        with:
          changed-files: |
            ./tests/data/default/src/package1/file.ts
            ./tests/data/default/src/package2/subfolder/file.ts
            ./tests/data/default/other/package4/file.ts
            ./tests/data/default/other/package5/file.ts
          all-packages: |
            ./tests/data/default/src/package1
            ./tests/data/default/src/package2
            ./tests/data/default/src/package3
          changed-packages-format: json

      - name: Assert changed-packages
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.test-run.outputs.changed-packages }}
          expected: |
            ["${{ github.workspace }}/tests/data/default/src/package1","${{ github.workspace }}/tests/data/default/src/package2"]

  e2e-method-all:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Test Run
        id: test-run
        uses: ./
        with:
          changed-files: |
            ./tests/data/default/src/package1/file.ts
          all-packages: |
            ./tests/data/default/src/*
          package-dependencies-resolution-method: all

      - name: Assert changed-packages
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.test-run.outputs.changed-packages }}
          expected: |
            ${{ github.workspace }}/tests/data/default/src/package1
            ${{ github.workspace }}/tests/data/default/src/package2
            ${{ github.workspace }}/tests/data/default/src/package3

  e2e-method-poetry-path:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Test Run
        id: test-run
        uses: ./
        with:
          changed-files: |
            ./tests/data/poetry-path/default/parent/file.ts
          all-packages: |
            ./tests/data/poetry-path/default/*
          package-dependencies-resolution-method: poetry-path

      - name: Assert changed-packages
        uses: nick-fields/assert-action@v2
        with:
          actual: ${{ steps.test-run.outputs.changed-packages }}
          expected: |
            ${{ github.workspace }}/tests/data/poetry-path/default/parent
            ${{ github.workspace }}/tests/data/poetry-path/default/child
            ${{ github.workspace }}/tests/data/poetry-path/default/grandchild

  e2e:
    runs-on: ubuntu-latest
    if: always() && !cancelled()

    needs:
      - e2e-default
      - e2e-all-packages-glob
      - e2e-changed-files-separator
      - e2e-all-packages-separator
      - e2e-changed-packages-list-separator
      - e2e-changed-packages-format-json
      - e2e-method-all
      - e2e-method-poetry-path

    steps:
      - name: Collect Results
        uses: ovsds/collect-needs-result-action@v1
        with:
          needs_json: ${{ toJson(needs) }}
          skip_allowed: false
